/* CREAR TABLA */
CREATE TABLE IMSA_PERSONA (
  ID NUMBER, 
  NOMBRE VARCHAR2(100),
  FECHA DATE
);

/* CREAR */
CREATE OR REPLACE PROCEDURE IMSA_PERSONA_CREAR (
  P_NOMBRE IN VARCHAR2,  
  P_FECHA IN DATE  
) AS 
  V_INDEX NUMBER;
BEGIN
  SELECT NVL(MAX(ID),0)+1 
  INTO V_INDEX
  FROM SYSTEM.IMSA_PERSONA;
  
  INSERT INTO SYSTEM.IMSA_PERSONA 
  VALUES(V_INDEX, P_NOMBRE, P_FECHA);
END;

/* ELIMINAR */
CREATE OR REPLACE PROCEDURE IMSA_PERSONA_ELIMINAR (
  P_ID NUMBER
) AS 
BEGIN
  
  DELETE FROM SYSTEM.IMSA_PERSONA 
  WHERE ID = P_ID;
  
END;

/* ACTUALIZAR */
CREATE OR REPLACE PROCEDURE IMSA_PERSONA_ACTUALIZAR (
  P_ID NUMBER,
  P_NOMBRE IN VARCHAR2,  
  P_FECHA IN DATE  
) AS 
BEGIN
  
  UPDATE SYSTEM.IMSA_PERSONA 
  SET NOMBRE = P_NOMBRE,
      FECHA = P_FECHA
  WHERE ID = P_ID;
  
END;

/* LISTAR */
CREATE OR REPLACE PROCEDURE IMSA_PERSONA_LISTAR (
  P_ID NUMBER,
  P_RECORDSET OUT SYS_REFCURSOR
) AS 
BEGIN

  OPEN P_RECORDSET FOR
    SELECT  ID, NOMBRE, FECHA
    FROM SYSTEM.IMSA_PERSONA 
    WHERE ID = NVL(P_ID, ID);
  
END;

SELECT * FROM SYSTEM.IMSA_PERSONA

CALL IMSA_PERSONA_LISTAR(1)

VARIABLE RC REFCURSOR;
EXEC IMSA_PERSONA_LISTAR(NULL, :RC );
PRINT RC

EXEC IMSA_PERSONA_LISTAR(:ID, :RC );

CALL IMSA_PERSONA_LISTAR(:ID, :RC )

CALL IMSA_PERSONA_CREAR('Jose', TO_DATE('15/09/2022','DD/MM/RRRR'));

CALL IMSA_PERSONA_CREAR('Arnoldo', TO_DATE('15/09/2022','DD/MM/RRRR'));

CALL IMSA_PERSONA_CREAR('Paola', TO_DATE('15/09/2022','DD/MM/RRRR'));

CALL IMSA_PERSONA_CREAR('Ricardo', TO_DATE('15/09/2022','DD/MM/RRRR'));

CALL IMSA_PERSONA_CREAR('Monica', TO_DATE('15/09/2022','DD/MM/RRRR'));


INSERT INTO SYSTEM.IMSA_PERSONA VALUES(1, 'Arnoldo', TO_DATE('15/09/2022', 'DD/MM/RRRR'));
INSERT INTO SYSTEM.IMSA_PERSONA VALUES(2, 'Ricardo', TO_DATE('15/09/2022', 'DD/MM/RRRR'));
INSERT INTO SYSTEM.IMSA_PERSONA VALUES(3, 'Jose', TO_DATE('15/09/2022', 'DD/MM/RRRR'));
INSERT INTO SYSTEM.IMSA_PERSONA VALUES(4, 'Paola', TO_DATE('15/09/2022', 'DD/MM/RRRR'));
INSERT INTO SYSTEM.IMSA_PERSONA VALUES(5, 'Monica', TO_DATE('15/09/2022', 'DD/MM/RRRR'));

SELECT ID, NOMBRE, FECHA FROM SYSTEM.IMSA_PERSONA

DELETE SYSTEM.IMSA_PERSONA;

SELECT NVL(MAX(ID),0)+1 FROM SYSTEM.IMSA_PERSONA



